# Generated by Django 5.0.1 on 2025-07-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('category', models.CharField(choices=[('array', 'Arrays'), ('string', 'Strings'), ('linkedlist', 'Linked Lists'), ('tree', 'Trees'), ('graph', 'Graphs'), ('dp', 'Dynamic Programming'), ('sorting', 'Sorting'), ('searching', 'Searching'), ('other', 'Other')], max_length=20)),
                ('examples', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('solution_approach', models.TextField(blank=True)),
                ('time_complexity', models.CharField(blank=True, max_length=50)),
                ('space_complexity', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
    ]
