# Generated by Django 5.0.1 on 2025-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsaquestion',
            name='leetcode_url',
            field=models.URLField(blank=True, help_text='Direct link to the LeetCode problem'),
        ),
    ]
