services:
  - type: web
    name: ai-interview-helper
    env: python
    plan: free  # or starter/pro
    buildCommand: "./build.sh"
    startCommand: "gunicorn ai_interview_helper.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ai_interview_helper.settings_render
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: GEMINI_API_KEY
        sync: false  # You'll set this manually in Render dashboard
