# Generated by Django 5.0.1 on 2025-07-20 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalInterviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('questions_data', models.JSONField()),
                ('answers_data', models.JSONField()),
                ('duration', models.IntegerField()),
                ('overall_score', models.IntegerField()),
                ('performance_level', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], max_length=20)),
                ('strengths', models.JSONField()),
                ('improvements', models.JSONField()),
                ('skill_scores', models.JSONField()),
                ('question_reviews', models.JSONField()),
                ('recommendations', models.JSONField()),
                ('questions_answered', models.IntegerField()),
                ('average_answer_length', models.IntegerField()),
                ('voice_answers_count', models.IntegerField()),
                ('text_answers_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
