# Generated by Django 5.0.1 on 2025-07-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_technicalinterviewreport'),
    ]

    operations = [
    ]
